# Generated by Django 4.2.4 on 2023-11-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='due_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
